# Generated by Django 3.2 on 2022-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=12, verbose_name='Пароль')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='application_from_type',
            field=models.CharField(choices=[('self', 'Сам'), ('other', '3-е лицо')], default='self', max_length=255, verbose_name='Форма подачи заявления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='ФИО на русском языке'),
        ),
    ]
